# Generated by Django 3.0.7 on 2020-07-04 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200703_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='_user_followed_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
