# Generated by Django 3.0.7 on 2020-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200702_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
