# Generated by Django 3.0.7 on 2020-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200704_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('yellow', 'yellow'), ('pink', 'pink')], default='green', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('montserratSubrayada', 'montserratSubrayada'), ('greatVibes', 'greatVibes'), ('bebasNeue', 'bebasNeue')], default='montserratSubrayada', max_length=50),
        ),
    ]
