# Generated by Django 3.0.7 on 2020-07-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200708_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('yellow', 'yellow'), ('pink', 'pink')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(blank=True, choices=[('montserratSubrayada', 'montserratSubrayada'), ('greatVibes', 'greatVibes'), ('bebasNeue', 'bebasNeue')], max_length=50, null=True),
        ),
    ]
