# Generated by Django 3.0.7 on 2020-07-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200708_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.RemoveField(
            model_name='card',
            name='font',
        ),
    ]
