# Generated by Django 3.0.7 on 2020-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200708_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='font',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
