# Generated by Django 3.0.7 on 2020-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200709_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border_style',
            field=models.CharField(blank=True, choices=[('solid', 'solid'), ('double', 'double'), ('dotted', 'dotted')], max_length=50, null=True),
        ),
    ]
