# Generated by Django 3.0.7 on 2020-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200709_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('yellow', 'yellow'), ('pink', 'pink'), ('blue', 'blue'), ('purple', 'purple')], max_length=50, null=True),
        ),
    ]
